esphome:
  name: "aktobis-wdh-310ekw"

esp8266:
  board: esp07

logger:
  hardware_uart: UART0_SWAP

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "aktobis-wdh-310ekw"
    password: !secret ap_password

captive_portal:

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

tuya:

switch:
  - platform: tuya
    id: aktobis_power
    name: "Netzschalter"
    switch_datapoint: 1

binary_sensor:
  - platform: tuya
    id: aktobis_tank_led
    name: "Behälter voll/entfernt"
    sensor_datapoint: 101
    icon: "mdi:cup-off-outline"
  - platform: tuya
    id: aktobis_defrost_led
    name: "Abtaumodus"
    sensor_datapoint: 102
    icon: "mdi:snowflake"

sensor:
  - platform: tuya
    id: aktobis_humidity
    name: "Luftfeuchtigkeit"
    sensor_datapoint: 6
    device_class: humidity
  - platform: tuya
    id: aktobis_temperature
    name: "Temperatur"
    sensor_datapoint: 7
    device_class: temperature

select:
  - platform: tuya
    id: aktobis_target_humidity
    name: "Zielfeuchtigkeit"
    icon: "mdi:water-percent"
    enum_datapoint: 3
    optimistic: true
    options:
      0: "30 %"
      1: "35 %"
      2: "40 %"
      3: "45 %"
      4: "50 %"
      5: "55 %"
      6: "60 %"
      7: "65 %"
      8: "70 %"
  - platform: tuya
    id: aktobis_fan
    name: "Lüfter"
    icon: "mdi:fan"
    enum_datapoint: 4
    optimistic: true
    options:
      0: "Niedrig"
      1: "Hoch"
